# Generated by Django 6.0.2 on 2026-05-15 15:55

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_num', models.IntegerField()),
                ('timepoint_id', models.CharField(db_index=True, editable=False, max_length=11)),
                ('phar_sa', models.BooleanField(blank=True, default=None, null=True)),
                ('rec_sa', models.BooleanField(blank=True, default=None, null=True)),
                ('rec_mac', models.BooleanField(blank=True, default=None, null=True)),
                ('rec_esbl', models.BooleanField(blank=True, default=None, null=True)),
                ('nas_sa', models.BooleanField(blank=True, default=None, null=True)),
                ('vag_sa', models.BooleanField(blank=True, default=None, null=True)),
                ('vag_mac', models.BooleanField(blank=True, default=None, null=True)),
                ('vag_esbl', models.BooleanField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"doxypep"."culture"',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_num', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('treatment', models.BooleanField(blank=True, default=None, null=True)),
                ('patient_type', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': '"doxypep"."patient"',
            },
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('Nas_SA', 'Nas SA'), ('Phar_SA', 'Phar SA'), ('Rec_SA', 'Rec SA'), ('Rec_Mac', 'Rec Mac'), ('Rec_ESBL', 'Rec ESBL'), ('Vag_SA', 'Vag SA'), ('Vag_Mac', 'Vag Mac'), ('Vag_ESBL', 'Vag ESBL')], max_length=10)),
                ('isolate_num', models.IntegerField(editable=False)),
                ('date', models.DateTimeField()),
                ('box', models.CharField(editable=False, max_length=25)),
                ('position', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('KBT', 'KB Tested'), ('FIN', 'Finished'), ('WGS', 'Sequenced')], default='NEW', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timepoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxypep.culture')),
            ],
            options={
                'db_table': '"doxypep"."isolate"',
                'unique_together': {('box', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Kb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gentamicin', models.IntegerField()),
                ('erithromycin', models.IntegerField()),
                ('tetracycline', models.IntegerField()),
                ('minocycline', models.IntegerField()),
                ('doxycycline', models.IntegerField()),
                ('clindamycin', models.IntegerField()),
                ('cefoxitin', models.IntegerField()),
                ('oxacillin', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('isolate_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_isolate_num', to='doxypep.isolate')),
            ],
        ),
        migrations.AddField(
            model_name='culture',
            name='patient_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxypep.patient'),
        ),
        migrations.CreateModel(
            name='TaggedAllele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Allele Tag',
                'db_table': '"doxypep"."tagged_allele"',
            },
        ),
        migrations.CreateModel(
            name='WGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sequenced', models.DateTimeField()),
                ('date_collected', models.DateTimeField()),
                ('sequence_type', models.CharField(max_length=25)),
                ('depth', models.FloatField()),
                ('need_resequencing', models.BooleanField(blank=True, default=None, null=True)),
                ('organism', models.CharField(max_length=50)),
                ('allele', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='doxypep.TaggedAllele', to='taggit.Tag', verbose_name='Tags')),
                ('isolate_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wgs_isolate_num', to='doxypep.isolate')),
            ],
            options={
                'verbose_name': 'WGS',
                'verbose_name_plural': 'WGS',
                'db_table': '"doxypep"."wgs"',
            },
        ),
        migrations.AddField(
            model_name='taggedallele',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doxypep.wgs'),
        ),
        migrations.AlterUniqueTogether(
            name='culture',
            unique_together={('patient_num', 'visit_num')},
        ),
    ]
