# Generated by Django 6.0.2 on 2026-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxypep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolate',
            name='original_label',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
