# Generated by Django 6.0.2 on 2026-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxypep', '0002_isolate_original_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isolate',
            name='sample_type',
            field=models.CharField(choices=[('Nas_SA', 'Nas SA'), ('Phar_SA', 'Phar SA'), ('Rec_SA', 'Rec SA'), ('Rec_Mac', 'Rec Mac'), ('Rec_ESBL', 'Rec ESBL'), ('Vag_SA', 'Vag SA'), ('Vag_Mac', 'Vag Mac'), ('Vag_ESBL', 'Vag ESBL'), ('Other', 'Other')], max_length=10),
        ),
    ]
