# Generated by Django 6.0.2 on 2026-05-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxypep', '0003_alter_isolate_sample_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='culture',
            table=None,
        ),
        migrations.AlterModelTable(
            name='isolate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taggedallele',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wgs',
            table=None,
        ),
    ]
