# Generated by Django 6.0.2 on 2026-05-20 14:12

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxypep', '0004_alter_culture_table_alter_isolate_table_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Participant',
        ),
        migrations.RenameModel(
            old_name='TaggedAllele',
            new_name='TaggedArg',
        ),
        migrations.AlterModelOptions(
            name='taggedarg',
            options={'verbose_name': 'Arg Tag'},
        ),
        migrations.RenameField(
            model_name='culture',
            old_name='patient_num',
            new_name='participant_id',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='patient_num',
            new_name='participant_id',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='patient_type',
            new_name='participant_type',
        ),
        migrations.RemoveField(
            model_name='wgs',
            name='allele',
        ),
        migrations.AddField(
            model_name='wgs',
            name='arg',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='doxypep.TaggedArg', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='culture',
            unique_together={('participant_id', 'visit_num')},
        ),
    ]
