--
-- PostgreSQL database dump
--

\restrict MLdnpcl6TruQwIzvnkrh2R0wjE8sRFNdUuqunPJlFE9exvEtv7u0xcxg20cskub

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: doxypep; Type: SCHEMA; Schema: -; Owner: uhlemann
--

CREATE SCHEMA doxypep;


ALTER SCHEMA doxypep OWNER TO uhlemann;

--
-- Name: freedberg; Type: SCHEMA; Schema: -; Owner: uhlemann
--

CREATE SCHEMA freedberg;


ALTER SCHEMA freedberg OWNER TO uhlemann;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: uhlemann
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO uhlemann;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: uhlemann
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE doxypep.auth_group OWNER TO uhlemann;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE doxypep.auth_group_permissions OWNER TO uhlemann;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE doxypep.auth_permission OWNER TO uhlemann;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE doxypep.auth_user OWNER TO uhlemann;

--
-- Name: auth_user_groups; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE doxypep.auth_user_groups OWNER TO uhlemann;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE doxypep.auth_user_user_permissions OWNER TO uhlemann;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE doxypep.django_admin_log OWNER TO uhlemann;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE doxypep.django_content_type OWNER TO uhlemann;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE doxypep.django_migrations OWNER TO uhlemann;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE doxypep.django_session OWNER TO uhlemann;

--
-- Name: doxypep_culture; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.doxypep_culture (
    id bigint NOT NULL,
    visit_num integer NOT NULL,
    timepoint_id character varying(11) NOT NULL,
    phar_sa boolean,
    rec_sa boolean,
    rec_mac boolean,
    rec_esbl boolean,
    nas_sa boolean,
    vag_sa boolean,
    vag_mac boolean,
    vag_esbl boolean,
    date timestamp with time zone NOT NULL,
    notes text,
    participant_id_id bigint NOT NULL
);


ALTER TABLE doxypep.doxypep_culture OWNER TO uhlemann;

--
-- Name: doxypep_culture_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.doxypep_culture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.doxypep_culture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doxypep_isolate; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.doxypep_isolate (
    id bigint NOT NULL,
    original_label character varying(25),
    sample_type character varying(10) NOT NULL,
    isolate_num integer NOT NULL,
    date timestamp with time zone NOT NULL,
    box character varying(25) NOT NULL,
    "position" integer NOT NULL,
    status character varying(3) NOT NULL,
    notes text,
    timepoint_id_id bigint NOT NULL
);


ALTER TABLE doxypep.doxypep_isolate OWNER TO uhlemann;

--
-- Name: doxypep_isolate_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.doxypep_isolate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.doxypep_isolate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doxypep_kb; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.doxypep_kb (
    id bigint NOT NULL,
    gentamicin integer NOT NULL,
    erithromycin integer NOT NULL,
    tetracycline integer NOT NULL,
    minocycline integer NOT NULL,
    doxycycline integer NOT NULL,
    clindamycin integer NOT NULL,
    cefoxitin integer NOT NULL,
    oxacillin integer NOT NULL,
    date timestamp with time zone NOT NULL,
    notes text,
    isolate_num_id bigint NOT NULL
);


ALTER TABLE doxypep.doxypep_kb OWNER TO uhlemann;

--
-- Name: doxypep_kb_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.doxypep_kb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.doxypep_kb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doxypep_participant; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.doxypep_participant (
    id bigint NOT NULL,
    participant_id character varying(8) NOT NULL,
    status boolean NOT NULL,
    treatment boolean,
    participant_type boolean
);


ALTER TABLE doxypep.doxypep_participant OWNER TO uhlemann;

--
-- Name: doxypep_participant_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.doxypep_participant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.doxypep_participant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doxypep_taggedarg; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.doxypep_taggedarg (
    id bigint NOT NULL,
    tag_id integer NOT NULL,
    content_object_id bigint NOT NULL
);


ALTER TABLE doxypep.doxypep_taggedarg OWNER TO uhlemann;

--
-- Name: doxypep_taggedarg_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.doxypep_taggedarg ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.doxypep_taggedarg_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doxypep_wgs; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.doxypep_wgs (
    id bigint NOT NULL,
    date_sequenced timestamp with time zone NOT NULL,
    date_collected timestamp with time zone NOT NULL,
    sequence_type character varying(25) NOT NULL,
    depth double precision NOT NULL,
    need_resequencing boolean,
    organism character varying(50) NOT NULL,
    isolate_num_id bigint NOT NULL
);


ALTER TABLE doxypep.doxypep_wgs OWNER TO uhlemann;

--
-- Name: doxypep_wgs_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.doxypep_wgs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.doxypep_wgs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taggit_tag; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.taggit_tag (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL
);


ALTER TABLE doxypep.taggit_tag OWNER TO uhlemann;

--
-- Name: taggit_tag_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.taggit_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.taggit_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taggit_taggeditem; Type: TABLE; Schema: doxypep; Owner: uhlemann
--

CREATE TABLE doxypep.taggit_taggeditem (
    id integer NOT NULL,
    object_id integer NOT NULL,
    content_type_id integer NOT NULL,
    tag_id integer NOT NULL
);


ALTER TABLE doxypep.taggit_taggeditem OWNER TO uhlemann;

--
-- Name: taggit_taggeditem_id_seq; Type: SEQUENCE; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE doxypep.taggit_taggeditem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME doxypep.taggit_taggeditem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: culture; Type: TABLE; Schema: freedberg; Owner: uhlemann
--

CREATE TABLE freedberg.culture (
    id bigint NOT NULL,
    vre_blue boolean NOT NULL,
    vre_pink boolean NOT NULL,
    kpc_blue boolean NOT NULL,
    kpc_pink boolean NOT NULL,
    kpc_white boolean NOT NULL,
    date timestamp with time zone NOT NULL,
    notes text,
    sample_id_id bigint NOT NULL
);


ALTER TABLE freedberg.culture OWNER TO uhlemann;

--
-- Name: culture_id_seq; Type: SEQUENCE; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE freedberg.culture ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME freedberg.culture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: isolate; Type: TABLE; Schema: freedberg; Owner: uhlemann
--

CREATE TABLE freedberg.isolate (
    id bigint NOT NULL,
    isolate_id character varying(7) NOT NULL,
    isolate_type character varying(10) NOT NULL,
    box character varying(25) NOT NULL,
    "position" integer NOT NULL,
    status character varying(3) NOT NULL,
    date timestamp with time zone NOT NULL,
    notes text,
    sample_id_id bigint NOT NULL
);


ALTER TABLE freedberg.isolate OWNER TO uhlemann;

--
-- Name: isolate_id_seq; Type: SEQUENCE; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE freedberg.isolate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME freedberg.isolate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sample; Type: TABLE; Schema: freedberg; Owner: uhlemann
--

CREATE TABLE freedberg.sample (
    id bigint NOT NULL,
    sample_id character varying(6) NOT NULL,
    sample_num integer NOT NULL,
    sample_type character varying(3) NOT NULL,
    sixteen_s boolean NOT NULL,
    extraction boolean,
    sixteen_s_finished boolean NOT NULL,
    date timestamp with time zone NOT NULL,
    box integer NOT NULL,
    "position" character varying(2) NOT NULL,
    notes text
);


ALTER TABLE freedberg.sample OWNER TO uhlemann;

--
-- Name: sample_id_seq; Type: SEQUENCE; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE freedberg.sample ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME freedberg.sample_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: doxypep_culture doxypep_culture_participant_id_id_visit_num_b672fd56_uniq; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_culture
    ADD CONSTRAINT doxypep_culture_participant_id_id_visit_num_b672fd56_uniq UNIQUE (participant_id_id, visit_num);


--
-- Name: doxypep_culture doxypep_culture_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_culture
    ADD CONSTRAINT doxypep_culture_pkey PRIMARY KEY (id);


--
-- Name: doxypep_isolate doxypep_isolate_box_position_3adaec04_uniq; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_isolate
    ADD CONSTRAINT doxypep_isolate_box_position_3adaec04_uniq UNIQUE (box, "position");


--
-- Name: doxypep_isolate doxypep_isolate_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_isolate
    ADD CONSTRAINT doxypep_isolate_pkey PRIMARY KEY (id);


--
-- Name: doxypep_kb doxypep_kb_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_kb
    ADD CONSTRAINT doxypep_kb_pkey PRIMARY KEY (id);


--
-- Name: doxypep_participant doxypep_participant_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_participant
    ADD CONSTRAINT doxypep_participant_pkey PRIMARY KEY (id);


--
-- Name: doxypep_taggedarg doxypep_taggedarg_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_taggedarg
    ADD CONSTRAINT doxypep_taggedarg_pkey PRIMARY KEY (id);


--
-- Name: doxypep_wgs doxypep_wgs_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_wgs
    ADD CONSTRAINT doxypep_wgs_pkey PRIMARY KEY (id);


--
-- Name: taggit_tag taggit_tag_name_key; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.taggit_tag
    ADD CONSTRAINT taggit_tag_name_key UNIQUE (name);


--
-- Name: taggit_tag taggit_tag_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.taggit_tag
    ADD CONSTRAINT taggit_tag_pkey PRIMARY KEY (id);


--
-- Name: taggit_tag taggit_tag_slug_key; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.taggit_tag
    ADD CONSTRAINT taggit_tag_slug_key UNIQUE (slug);


--
-- Name: taggit_taggeditem taggit_taggeditem_content_type_id_object_id_tag_id_4bb97a8e_uni; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_content_type_id_object_id_tag_id_4bb97a8e_uni UNIQUE (content_type_id, object_id, tag_id);


--
-- Name: taggit_taggeditem taggit_taggeditem_pkey; Type: CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_pkey PRIMARY KEY (id);


--
-- Name: culture culture_pkey; Type: CONSTRAINT; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE ONLY freedberg.culture
    ADD CONSTRAINT culture_pkey PRIMARY KEY (id);


--
-- Name: culture culture_sample_id_id_adde098d_uniq; Type: CONSTRAINT; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE ONLY freedberg.culture
    ADD CONSTRAINT culture_sample_id_id_adde098d_uniq UNIQUE (sample_id_id);


--
-- Name: isolate isolate_box_position_473acd4e_uniq; Type: CONSTRAINT; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE ONLY freedberg.isolate
    ADD CONSTRAINT isolate_box_position_473acd4e_uniq UNIQUE (box, "position");


--
-- Name: isolate isolate_pkey; Type: CONSTRAINT; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE ONLY freedberg.isolate
    ADD CONSTRAINT isolate_pkey PRIMARY KEY (id);


--
-- Name: sample sample_pkey; Type: CONSTRAINT; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE ONLY freedberg.sample
    ADD CONSTRAINT sample_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_group_name_a6ea08ec_like ON doxypep.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON doxypep.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON doxypep.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON doxypep.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_user_groups_group_id_97559544 ON doxypep.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON doxypep.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON doxypep.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON doxypep.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX auth_user_username_6821ab7c_like ON doxypep.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON doxypep.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON doxypep.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX django_session_expire_date_a5c62663 ON doxypep.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX django_session_session_key_c0390e0f_like ON doxypep.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: doxypep_culture_participant_id_id_cc7540ca; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_culture_participant_id_id_cc7540ca ON doxypep.doxypep_culture USING btree (participant_id_id);


--
-- Name: doxypep_culture_timepoint_id_5526f803; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_culture_timepoint_id_5526f803 ON doxypep.doxypep_culture USING btree (timepoint_id);


--
-- Name: doxypep_culture_timepoint_id_5526f803_like; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_culture_timepoint_id_5526f803_like ON doxypep.doxypep_culture USING btree (timepoint_id varchar_pattern_ops);


--
-- Name: doxypep_isolate_timepoint_id_id_2098db22; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_isolate_timepoint_id_id_2098db22 ON doxypep.doxypep_isolate USING btree (timepoint_id_id);


--
-- Name: doxypep_kb_isolate_num_id_9cf90378; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_kb_isolate_num_id_9cf90378 ON doxypep.doxypep_kb USING btree (isolate_num_id);


--
-- Name: doxypep_taggedarg_content_object_id_50d5c863; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_taggedarg_content_object_id_50d5c863 ON doxypep.doxypep_taggedarg USING btree (content_object_id);


--
-- Name: doxypep_taggedarg_tag_id_6b121078; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_taggedarg_tag_id_6b121078 ON doxypep.doxypep_taggedarg USING btree (tag_id);


--
-- Name: doxypep_wgs_isolate_num_id_4cce2939; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX doxypep_wgs_isolate_num_id_4cce2939 ON doxypep.doxypep_wgs USING btree (isolate_num_id);


--
-- Name: taggit_tag_name_58eb2ed9_like; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX taggit_tag_name_58eb2ed9_like ON doxypep.taggit_tag USING btree (name varchar_pattern_ops);


--
-- Name: taggit_tag_slug_6be58b2c_like; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX taggit_tag_slug_6be58b2c_like ON doxypep.taggit_tag USING btree (slug varchar_pattern_ops);


--
-- Name: taggit_tagg_content_8fc721_idx; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX taggit_tagg_content_8fc721_idx ON doxypep.taggit_taggeditem USING btree (content_type_id, object_id);


--
-- Name: taggit_taggeditem_content_type_id_9957a03c; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX taggit_taggeditem_content_type_id_9957a03c ON doxypep.taggit_taggeditem USING btree (content_type_id);


--
-- Name: taggit_taggeditem_object_id_e2d7d1df; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX taggit_taggeditem_object_id_e2d7d1df ON doxypep.taggit_taggeditem USING btree (object_id);


--
-- Name: taggit_taggeditem_tag_id_f4f5b767; Type: INDEX; Schema: doxypep; Owner: uhlemann
--

CREATE INDEX taggit_taggeditem_tag_id_f4f5b767 ON doxypep.taggit_taggeditem USING btree (tag_id);


--
-- Name: culture_sample_id_id_adde098d; Type: INDEX; Schema: freedberg; Owner: uhlemann
--

CREATE INDEX culture_sample_id_id_adde098d ON freedberg.culture USING btree (sample_id_id);


--
-- Name: isolate_sample_id_id_6ad93cff; Type: INDEX; Schema: freedberg; Owner: uhlemann
--

CREATE INDEX isolate_sample_id_id_6ad93cff ON freedberg.isolate USING btree (sample_id_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES doxypep.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES doxypep.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES doxypep.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES doxypep.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES doxypep.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES doxypep.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES doxypep.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES doxypep.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES doxypep.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doxypep_culture doxypep_culture_participant_id_id_cc7540ca_fk_doxypep_p; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_culture
    ADD CONSTRAINT doxypep_culture_participant_id_id_cc7540ca_fk_doxypep_p FOREIGN KEY (participant_id_id) REFERENCES doxypep.doxypep_participant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doxypep_isolate doxypep_isolate_timepoint_id_id_2098db22_fk_doxypep_culture_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_isolate
    ADD CONSTRAINT doxypep_isolate_timepoint_id_id_2098db22_fk_doxypep_culture_id FOREIGN KEY (timepoint_id_id) REFERENCES doxypep.doxypep_culture(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doxypep_kb doxypep_kb_isolate_num_id_9cf90378_fk_doxypep_isolate_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_kb
    ADD CONSTRAINT doxypep_kb_isolate_num_id_9cf90378_fk_doxypep_isolate_id FOREIGN KEY (isolate_num_id) REFERENCES doxypep.doxypep_isolate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doxypep_taggedarg doxypep_taggedarg_content_object_id_50d5c863_fk_doxypep_wgs_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_taggedarg
    ADD CONSTRAINT doxypep_taggedarg_content_object_id_50d5c863_fk_doxypep_wgs_id FOREIGN KEY (content_object_id) REFERENCES doxypep.doxypep_wgs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doxypep_taggedarg doxypep_taggedarg_tag_id_6b121078_fk_taggit_tag_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_taggedarg
    ADD CONSTRAINT doxypep_taggedarg_tag_id_6b121078_fk_taggit_tag_id FOREIGN KEY (tag_id) REFERENCES doxypep.taggit_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: doxypep_wgs doxypep_wgs_isolate_num_id_4cce2939_fk_doxypep_isolate_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.doxypep_wgs
    ADD CONSTRAINT doxypep_wgs_isolate_num_id_4cce2939_fk_doxypep_isolate_id FOREIGN KEY (isolate_num_id) REFERENCES doxypep.doxypep_isolate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: taggit_taggeditem taggit_taggeditem_content_type_id_9957a03c_fk_django_co; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_content_type_id_9957a03c_fk_django_co FOREIGN KEY (content_type_id) REFERENCES doxypep.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: taggit_taggeditem taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id; Type: FK CONSTRAINT; Schema: doxypep; Owner: uhlemann
--

ALTER TABLE ONLY doxypep.taggit_taggeditem
    ADD CONSTRAINT taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id FOREIGN KEY (tag_id) REFERENCES doxypep.taggit_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: culture culture_sample_id_id_adde098d_fk_sample_id; Type: FK CONSTRAINT; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE ONLY freedberg.culture
    ADD CONSTRAINT culture_sample_id_id_adde098d_fk_sample_id FOREIGN KEY (sample_id_id) REFERENCES freedberg.sample(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: isolate isolate_sample_id_id_6ad93cff_fk_culture_id; Type: FK CONSTRAINT; Schema: freedberg; Owner: uhlemann
--

ALTER TABLE ONLY freedberg.isolate
    ADD CONSTRAINT isolate_sample_id_id_6ad93cff_fk_culture_id FOREIGN KEY (sample_id_id) REFERENCES freedberg.culture(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: uhlemann
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict MLdnpcl6TruQwIzvnkrh2R0wjE8sRFNdUuqunPJlFE9exvEtv7u0xcxg20cskub

